language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ssherman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ssherman/react-test npm run test


after_success:
  - docker build -t wtf242/multi-client ./client
  - docker build -t wtf242/multi-nginx ./nginx
  - docker build -t wtf242/multi-server ./server
  - docker build -t wtf242/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wtf242/multi-client
  - docker push wtf242/multi-nginx
  - docker push wtf242/multi-server
  - docker push wtf242/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "react-test"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-307057572356"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY